# Generated by Django 5.2.3 on 2025-06-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('food_item', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('pickup_address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('expiry_time', models.DateTimeField()),
                ('is_picked', models.BooleanField(default=False)),
            ],
        ),
    ]
