# Generated by Django 5.2.3 on 2025-06-20 05:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor_name',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='is_picked',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='quantity',
        ),
        migrations.AddField(
            model_name='donation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='food_type',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian'), ('mixed', 'Mixed')], default='veg', max_length=10),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='matched_recipient_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='pincode',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='quantity_kg',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='spice_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('picked', 'Picked Up'), ('delivered', 'Delivered'), ('composted', 'Composted'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
    ]
